apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelo-mcp
  namespace: vertikon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelo-mcp
  template:
    metadata:
      labels:
        app: modelo-mcp
    spec:
      containers:
        - name: modelo-mcp
          image: vertikon/modelo-mcp:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "modelo-mcp"
            - name: NATS_URL
              value: "nats://nats:4222"
          volumeMounts:
            - name: cfg
              mountPath: /app/configs
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: cfg
          configMap:
            name: modelo-mcp-config
