apiVersion: v1
kind: Service
metadata:
  name: {{MCP_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{MCP_NAME}}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: {{MCP_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{MCP_NAME}}-metrics
  namespace: {{NAMESPACE}}
  labels:
    app: {{MCP_NAME}}
    monitoring: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: {{MCP_NAME}}