apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modelo-mcp.fullname" . }}
  labels:
    {{- include "modelo-mcp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "modelo-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "modelo-mcp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
